sample rewrite file
moevm/yandex_utils pull request #5
Opened 2024-07-22 10:23 UTC by thehighestmath

2024-07-22 10:58 UTC, zmm commented on rewrite_file_on_disk.py
> +client.upload('example_table.csv', 'table.csv', overwrite=True)
А есть ли возможность использовать уникальные идентификаторы файлов? Так как у нас в теории может быть много авторов (много дисков), разные каталоги и тд)

2024-07-22 11:00 UTC, zmm commented on requirements.txt
Добавьте используемую версию библиотеки yadisk

2024-07-22 11:01 UTC, thehighestmath commented on rewrite_file_on_disk.py
> +client.upload('example_table.csv', 'table.csv', overwrite=True)
Второй параметр метода это путь назначения
В примере таблица загружается в корень диска

2024-07-22 11:02 UTC, thehighestmath commented on requirements.txt
Файл забыл заполнить

2024-07-22 11:25 UTC, zmm commented on rewrite_file_on_disk.py
> +client.upload('example_table.csv', 'table.csv', overwrite=True)
А если я вам зашарил свой диск, чтобы вы в нем правили мою таблицу - как будет выглядеть путь?

2024-07-22 11:27 UTC, thehighestmath commented on rewrite_file_on_disk.py
> +client.upload('example_table.csv', 'table.csv', overwrite=True)
Хм, надо подумать как быть в таком случае

2024-07-24 14:44 UTC, zmm requested changes
Разместите пример в отдельном каталоге

2025-04-16 12:40 UTC, closed without merging